name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: srbhr/metrics@main
        with:
          filename: metrics.classic.svg
          token: ${{ secrets.GH_METRICS }}
          name: Full-year calendar
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
